### ISSUE TITLE
Unix mode connection not working

### ISSUE THREAD

**Issue by sratatata** [google/vpn-reverse-tether#1]
```
adb forward /tmp/vpntether localabstract:vpntether
error: cannot bind to socket: Resource temporarily unavailable
```

Means that /tmp/vpntether is not created. When trying to use this tool: 

```
Connect to tunnel: No such file or directory
```

I've trying switching to TCP mode. But those not working on my 4.4 Kitkat device, but on 5.0.1 is working. 
No idea why... 

Could some one more experienced help me solve my issues?

**Comment by szym** [comment]
Looking at the `run.sh` script, I'm having trouble figuring out how it would execute

```
  adb forward /tmp/vpntether localabstract:vpntether
```

The script is:

```
  $ADB forward $LOCAL_ADDR_FORWARD localabstract:$ANDROID_SOCK
```

And `LOCAL_ADDR_FORWARD` is either `tcp:$LOCAL_PORT` or `localabstract:$ANDROID_SOCK`.

Assuming the script was not modified, can you check your environment variables? Maybe run `env run.sh` ?

**Comment by sratatata** [comment]
You are right I've done it wrong. (I was running above code separately when debugging, why run.sh run is not working). 
In fact when I'm running `./run.sh run`

```
>  ./run.sh run
Connect to tunnel: No such file or directory
```

I've checked that after setup there is no /tmp/vpntether file.

However I found such thing: Samsung Galaxy Note 4.3 is working with your program in tcp mode, Samsung A5 with Android 4.4 is not working in any mode and Samsung Galaxy s5 with Android 5.0.1 is working only in tcp mode. I'm a little confused now. 

Only source modification I made are: 

```
#: ${EXT_DEV:=eth0} changed into
EXT_DEV:=em1
```

I've didn't change any env variables (more handy for me was change them in source code - for now).

**Comment by szym** [comment]
```
  Connect to tunnel: No such file or directory
```

This suggests that the tunnel endpoint did not show up on the host. The default mode is `tcp` so you should not expect `/tmp/vpntether` UNIX socket. Instead, there should be a TCP socket listening on port 7890. Check with netstat that after running `./run.sh setup` there's one. The command that should open up this port is:

```
  adb forward tcp:7890 localabstract:vpntether
```

If this does not create the listening socket, there could be an issue with the adb service on your phone.

**Comment by sratatata** [comment]
I think that this is adb service issue.

**Comment by ashwinvis** [comment]
I run a rooted stock Android 6 on LG G3 and I tried to make this work. I have the same issue, same error, and my adb works fine. What else could be wrong?

The changes I made are listed below

```

    diff --git a/AndroidManifest.xml b/AndroidManifest.xml
    index 429bfcd..ad80b4b 100644
    --- a/AndroidManifest.xml
    +++ b/AndroidManifest.xml
    @@ -19,7 +19,7 @@
               android:versionName="0.1" android:versionCode="1"
               package="com.google.android.vpntether">
       <uses-permission android:name="android.permission.INTERNET"/>
    -  <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="17"/>
    +  <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="23"/>

    diff --git a/project.properties b/project.properties
    index a3ee5ab..916037e 100644
    --- a/project.properties
    +++ b/project.properties
    @@ -11,4 +11,4 @@
     # Project target.
    -target=android-17
    +target=android-23

    diff --git a/run.sh b/run.sh
    index 60aeed4..eea3f4a 100755
    --- a/run.sh
    +++ b/run.sh
    @@ -4,7 +4,7 @@
     : ${LOCAL_PORT:=7890}
     : ${ANDROID_SOCK:=vpntether}

    -: ${EXT_DEV:=eth0}
    +: ${EXT_DEV:=enp0s20u2}

```
